### ISSUE TITLE
Could not open cp_settings generic class . . .

### ISSUE THREAD

**Issue by Albretch** [xbib/marc#11]
OK, I followed the installation instructions on your site: https://gradle.org/install/
 and everything went fine, but after github(bing) https://github.com/xbib/marc and following their instructions to compile their java packages:

 https://github.com/xbib/marc#readme

 I got what seem to be two (probably related) errors:
 1) Could not open cp_settings generic class ...
 2) Unsupported class file major version 63

$ ./gradlew --scan  test -Dtest.single=MarcFieldFilterTest

FAILURE: Build failed with an exception.

* What went wrong:
Could not open cp_settings generic class cache for settings file '/media/cornuni47/LklWb/com/github/xbib/marc/settings.gradle' (/home/user/.gradle/caches/7.5.1/scripts/6k6glqurv5x00gbc6tyoftdxy).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 504ms

$ which gradle
/media/cornuni47/turk/sw/gradle/gradle-8.0.2/bin/gradle

$ gradle --version

------------------------------------------------------------
Gradle 8.0.2
------------------------------------------------------------

Build time:   2023-03-03 16:41:37 UTC
Revision:     7d6581558e226a580d91d399f7dfb9e3095c2b1d

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          19.0.1 (GraalVM Community 19.0.1+10-jvmci-22.3-b08)
OS:           Linux 5.10.0-18-amd64 amd64

$

**Comment by jprante** [comment]
Thanks for the report. I use OpenJDK 17.0.6 and Gradle 7.5.1, but will upgrade to Gradle 8+ soon. Please be patient.

I'm not sure if I will try also OpenJDK 19+ because I want to only support LTS versions.

**Comment by jprante** [comment]
Upgrade to Gradle 8+ was easier than suspected.

https://github.com/xbib/marc/commit/40e6051a40c9d7ba242fdc7c4b514063f57bb4d4
