### ISSUE TITLE
MARC JSON to MARC (or MARCXML)

### ISSUE THREAD

**Issue by zazi** [xbib/marc#4]
I'm not sure, whether it's already possible, but can I also transform the resulting MARC JSON (transformed via xbib/marc) back to MARC (or MARCXML)?

**Comment by jprante** [comment]
Sure, all content and structure information is kept, there is a round trip test that can be used as a blueprint https://github.com/xbib/marc/blob/master/src/test/java/org/xbib/marc/MarcRoundTripTest.java
