### ISSUE TITLE
processing of (binary) MARC records with empty subfields corrupts JSON output

### ISSUE THREAD

**Issue by zazi** [xbib/marc#7]
Sometimes we came along (binary) MARC records that do not have a value in a subfield, i.e., there's only the MARC code, but no value. When we process these records with xbib/marc the resulting JSON is a bit broken, i.e., in that case xbib/marc "eats" all other existing subfields of this datafield and returns only the subfield (MARC code) with the empty value, i.e., without a value.
In the following is an example of RISM:
- [rism_190101037.mrc](https://raw.githubusercontent.com/zazi/marc2jsonl/empty_subfields/src/test/resources/rism_190101037.mrc) (binary MARC record)
- [rism_190101037.xml](https://raw.githubusercontent.com/zazi/marc2jsonl/empty_subfields/src/test/resources/rism_190101037.xml) (MARCXML record)
- [rism_190101037.ldj](https://raw.githubusercontent.com/zazi/marc2jsonl/empty_subfields/src/test/resources/rism_190101037.ldj) (line-delimited JSON (output) record)
- [rism_190101037.json](https://raw.githubusercontent.com/zazi/marc2jsonl/empty_subfields/src/test/resources/rism_190101037.json) (JSON (output) record)

as one can see, in the source MARCXML file datafield 856 looks like

    <datafield tag="856" ind1="4" ind2="0">
        <subfield code="u">http://www.muslib.se/ebibliotek/roman/browsevol.php?lang=en&amp;by=volymid&amp;volymid=Ro+51</subfield>
        <subfield code="z"></subfield>
    </datafield>

and in the output JSON file datafield 856 looks like

      "856": [
        "z"
      ]

i.e. subfield "u" is completely missing (/"eaten")

//cc @boerni667 @jnauber

**Comment by jprante** [comment]
It was an offset-by-one issue, fixed now.
