### ISSUE TITLE
processing of (binary) MARC records does not preserve natural order of subfields in JSON output

### ISSUE THREAD

**Issue by zazi** [xbib/marc#8]
currently, the natural order of subfields in a datafield is not preserved in the JSON output of a (binary) MARC records transformation. Multiple values of a subfield of a certain key are put together in one JSON array (for the values of the subfield), but should be kept separate (in separate JSON objects) as it is given by its natural order.
In the following is an example, where the natural order of the subfields of MARC field 245 is 'a' - 'n' - 'p' - 'n' - 'p' - 'c':

- [test_ubl.mrc](https://raw.githubusercontent.com/zazi/marc2jsonl/subfields_natural_order/src/test/resources/test_ubl.mrc) (binary MARC record)
- [test_ubl.xml](https://raw.githubusercontent.com/zazi/marc2jsonl/subfields_natural_order/src/test/resources/test_ubl.xml) (MARCXML record)
- [test_ubl.ldj](https://raw.githubusercontent.com/zazi/marc2jsonl/subfields_natural_order/src/test/resources/test_ubl.ldj) (current line-delimited JSON (output) record)
- [test_ubl.json](https://raw.githubusercontent.com/zazi/marc2jsonl/subfields_natural_order/src/test/resources/test_ubl.json) (current JSON (output) record)
- [test_ubl_-_natural_subfield_ordner.ldj](https://raw.githubusercontent.com/zazi/marc2jsonl/subfields_natural_order/src/test/resources/test_ubl_-_natural_subfield_ordner.ldj) (proposed line-delimited JSON (output) record - to keep the natural order of the subfields)
- [test_ubl_-_natural_subfield_ordner.json](https://raw.githubusercontent.com/zazi/marc2jsonl/subfields_natural_order/src/test/resources/test_ubl_-_natural_subfield_ordner.json) (proposed JSON (output) record - to keep the natural order of the subfields)

we've tested the proposed (line-delimited) JSON record for elasticsearch search indexing - and it works (...and is searchable as good/bad as before ... ;) )

//cc @boerni667 @jnauber

**Comment by jprante** [comment]
I just added a "duplicate key mode" in MarcJSONWriter for situations where duplicate JSON keys can be acceptable. For example, writing MARC in JSON as intended by cataloging rules.

Note that duplicate JSON keys are not accepted by Elasticsearch (at least in recent versions, in older versions the indexing is erroneous) https://discuss.elastic.co/t/json-technically-allows-for-duplicate-keys-do-elasticsearch-documents/118526

**Comment by zazi** [comment]
From my understanding, it's not a duplicated JSON key (see [test_ubl_-_natural_subfield_ordner.json](https://raw.githubusercontent.com/zazi/marc2jsonl/subfields_natural_order/src/test/resources/test_ubl_-_natural_subfield_ordner.json)), because each subfield has it's own JSON object in the JSON array of subfields. It would only be a duplicated key, if it is in the same JSON object, or?
That's why, I still think that the proposed serialisation is valid.
Anyway, as far as I can review the huge changeset of #414abce it looks correct, i.e., as proposed ;)
thanks!
